

use mydb;

CREATE TABLE BBS(
	SEQ INT auto_increment PRIMARY KEY,
    ID VARCHAR(50) NOT NULL,
    
    REF	  DECIMAL(8) NOT NULL,
    STEP  DECIMAL(8) NOT NULL,
    DEPTH DECIMAL(8) NOT NULL,
    
    TITLE 	VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    WDATE	TIMESTAMP NOT NULL,
    
    DEL		DECIMAL(1) NOT NULL,
    READCOUNT DECIMAL(8) NOT NULL
);


ALTER TABLE BBS
ADD foreign key(ID) REFERENCES MEMBER(ID);


SELECT SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, WDATE, DEL, READCOUNT
  FROM ( SELECT ROW_NUMBER() OVER (ORDER BY REF DESC, STEP ASC) AS RNUM,
  		        SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, WDATE, DEL, READCOUNT
  		   FROM BBS 
  		  ORDER BY REF DESC, STEP ASC
  		) A
 WHERE RNUM BETWEEN 1 AND 20; 
 